package com.eqms.changecontrol.dto;

import java.time.Instant;
import java.util.List;
import java.util.Set;

import com.eqms.changecontrol.ChangeImpactTask;
import com.eqms.changecontrol.ChangeControl;

public record ChangeControlResponse(
        Long id,
        String changeNumber,
        String title,
        String type,
        String status,
        int version,
        String description,
        String locationName,
        String purposeOfChange,
        Instant regulatoryMandateEffectiveDate,
        String regulatoryMandateSource,
        String changeCategory,
        String relatedMarket,
        String relatedCustomer,
        String vendorCode,
        String vendorName,
        String productItemCode,
        String productItemDescription,
        String equipmentIdNumber,
        String equipmentName,
        String documentName,
        String documentNumber,
        String currentStatusBrief,
        String proposedChangeBrief,
        String justification,
        String changeNature,
        String temporaryChangePeriod,
        boolean effectivenessCheckRequired,
        Instant targetImplementationDate,
        String changeOwner,
        String changeOwnerHod,
        String qaResponsible,
        Set<String> involvedDepartments,
        List<ImpactTaskResponse> impactTasks,
        String radAssessmentRequired,
        String customerCgAssessmentRequired,
        String customerCgComments,
        String qaAssessmentBy,
        Instant qaAssessmentOn,
        String internalCustomer,
        String changeAcceptance,
        String qaComment,
        String recommendations,
        String qpComments,
        String variationClassification,
        String documentsRequestedForFiling,
        String recommendationForRelease,
        String otherRecommendations,
        String radAssessment,
        String otherDepartmentsReview,
        String finalQaDecision,
        Instant qaReviewDate,
        String qaReviewer,
        Instant implementedDate,
        String implementationDetails,
        String implementationReview,
        String actionConfirmationComment,
        Instant changeEffectiveDate,
        String closureRemarks,
        String batchArNumber,
        String productMaterialCode,
        String productMaterialName,
        String closedByName,
        Instant closedDate,
        Long createdBy,
        Long submittedBy,
        Instant createdAt,
        Instant updatedAt
) {
    public static ChangeControlResponse from(ChangeControl c) {
        return new ChangeControlResponse(
                c.getId(),
                c.getChangeNumber(),
                c.getTitle(),
                c.getChangeType().name(),
                c.getChangeStatus().name(),
                c.getVersion(),
                c.getDescription(),
                c.getLocationName(),
                c.getPurposeOfChange(),
                c.getRegulatoryMandateEffectiveDate(),
                c.getRegulatoryMandateSource(),
                c.getChangeCategory(),
                c.getRelatedMarket(),
                c.getRelatedCustomer(),
                c.getVendorCode(),
                c.getVendorName(),
                c.getProductItemCode(),
                c.getProductItemDescription(),
                c.getEquipmentIdNumber(),
                c.getEquipmentName(),
                c.getDocumentName(),
                c.getDocumentNumber(),
                c.getCurrentStatusBrief(),
                c.getProposedChangeBrief(),
                c.getJustification(),
                c.getChangeNature(),
                c.getTemporaryChangePeriod(),
                c.isEffectivenessCheckRequired(),
                c.getTargetImplementationDate(),
                c.getChangeOwner(),
                c.getChangeOwnerHod(),
                c.getQaResponsible(),
                Set.copyOf(c.getInvolvedDepartments()),
                c.getImpactTasks().stream().map(ImpactTaskResponse::from).toList(),
                c.getRadAssessmentRequired(),
                c.getCustomerCgAssessmentRequired(),
                c.getCustomerCgComments(),
                c.getQaAssessmentBy(),
                c.getQaAssessmentOn(),
                c.getInternalCustomer(),
                c.getChangeAcceptance(),
                c.getQaComment(),
                c.getRecommendations(),
                c.getQpComments(),
                c.getVariationClassification(),
                c.getDocumentsRequestedForFiling(),
                c.getRecommendationForRelease(),
                c.getOtherRecommendations(),
                c.getRadAssessment(),
                c.getOtherDepartmentsReview(),
                c.getFinalQaDecision(),
                c.getQaReviewDate(),
                c.getQaReviewer(),
                c.getImplementedDate(),
                c.getImplementationDetails(),
                c.getImplementationReview(),
                c.getActionConfirmationComment(),
                c.getChangeEffectiveDate(),
                c.getClosureRemarks(),
                c.getBatchArNumber(),
                c.getProductMaterialCode(),
                c.getProductMaterialName(),
                c.getClosedByName(),
                c.getClosedDate(),
                c.getCreatedBy(),
                c.getSubmittedBy(),
                c.getCreatedAt(),
                c.getUpdatedAt());
    }

    public record ImpactTaskResponse(
            Integer checkpointNo,
            String impactArea,
            String applicability,
            String proposedTask,
            String taskAssignee,
            String remarks
    ) {
        static ImpactTaskResponse from(ChangeImpactTask task) {
            return new ImpactTaskResponse(task.getCheckpointNo(), task.getImpactArea(),
                    task.getApplicability(), task.getProposedTask(), task.getTaskAssignee(), task.getRemarks());
        }
    }
}
