package com.eqms.capa.dto;

import java.time.Instant;

import com.eqms.capa.Capa;

public record CapaResponse(
        Long id,
        String capaNumber,
        String title,
        String source,
        String status,
        int version,
        String description,
        String rootCause,
        Instant eventDate,
        String priority,
        String aboutType,
        String aboutReference,
        String aboutDetails,
        String partyType,
        String partyFirstName,
        String partyLastName,
        String partyJobTitle,
        String partyCompany,
        String partyEmail,
        String partyPhone,
        String containmentDetails,
        String documentReferences,
        String keywords,
        String correctiveActionPlan,
        String preventiveActionPlan,
        Long assignedTo,
        String assignmentStatus,
        String assignmentComment,
        boolean effectivenessCheckRequired,
        String effectivenessCheckResult,
        Instant dueDate,
        Instant closedDate,
        Long createdBy,
        Long submittedBy,
        Instant createdAt,
        Instant updatedAt
) {
    public static CapaResponse from(Capa c) {
        return new CapaResponse(
                c.getId(),
                c.getCapaNumber(),
                c.getTitle(),
                c.getSource().name(),
                c.getCapaStatus().name(),
                c.getVersion(),
                c.getDescription(),
                c.getRootCause(),
                c.getEventDate(),
                c.getPriority(),
                c.getAboutType(),
                c.getAboutReference(),
                c.getAboutDetails(),
                c.getPartyType(),
                c.getPartyFirstName(),
                c.getPartyLastName(),
                c.getPartyJobTitle(),
                c.getPartyCompany(),
                c.getPartyEmail(),
                c.getPartyPhone(),
                c.getContainmentDetails(),
                c.getDocumentReferences(),
                c.getKeywords(),
                c.getCorrectiveActionPlan(),
                c.getPreventiveActionPlan(),
                c.getAssignedTo(),
                c.getAssignmentStatus(),
                c.getAssignmentComment(),
                c.isEffectivenessCheckRequired(),
                c.getEffectivenessCheckResult(),
                c.getDueDate(),
                c.getClosedDate(),
                c.getCreatedBy(),
                c.getSubmittedBy(),
                c.getCreatedAt(),
                c.getUpdatedAt());
    }
}
