package com.eqms.audits;

public enum ReasonForAudit {
    SCHEDULED_PROGRAMME,
    RISK_BASED,
    FOLLOW_UP,
    SUPPLIER_QUALIFICATION,
    COMPLAINT_TRIGGER,
    DEVIATION_TRIGGER,
    CAPA_FOLLOW_UP,
    REGULATORY_REQUIREMENT,
    MANAGEMENT_REQUEST,
    OTHER
}
