package com.eqms.products.dto;

import java.time.Instant;

import com.eqms.products.Product;

public record ProductResponse(
        Long id,
        String productCode,
        String name,
        String dosageForm,
        String productType,
        String category,
        String strength,
        String description,
        String intendedUse,
        String criticality,
        Long ownerId,
        String department,
        String siteLocation,
        String revision,
        String specificationReference,
        String specificationStatus,
        String storageRequirements,
        String shelfLife,
        boolean expiryRequired,
        boolean qcTestingRequired,
        boolean batchLotTrackingRequired,
        String regulatoryCustomerRequirements,
        String notes,
        String registrationNumber,
        String status,
        Long approvedBy,
        Instant approvedAt,
        java.time.LocalDate nextReviewDate,
        int version,
        Long createdBy,
        Long submittedBy,
        Instant createdAt,
        Instant updatedAt
) {
    public static ProductResponse from(Product p) {
        return new ProductResponse(
                p.getId(),
                p.getProductCode(),
                p.getName(),
                p.getDosageForm().name(),
                p.getProductType(),
                p.getCategory(),
                p.getStrength(),
                p.getDescription(),
                p.getIntendedUse(),
                p.getCriticality().name(),
                p.getOwnerId(),
                p.getDepartment(),
                p.getSiteLocation(),
                p.getRevision(),
                p.getSpecificationReference(),
                p.getSpecificationStatus(),
                p.getStorageRequirements(),
                p.getShelfLife(),
                p.isExpiryRequired(),
                p.isQcTestingRequired(),
                p.isBatchLotTrackingRequired(),
                p.getRegulatoryCustomerRequirements(),
                p.getNotes(),
                p.getRegistrationNumber(),
                p.getProductStatus().name(),
                p.getApprovedBy(),
                p.getApprovedAt(),
                p.getNextReviewDate(),
                p.getVersion(),
                p.getCreatedBy(),
                p.getSubmittedBy(),
                p.getCreatedAt(),
                p.getUpdatedAt());
    }
}
