package com.eqms.documents;

import java.time.Instant;

import org.hibernate.annotations.SQLDelete;
import org.hibernate.annotations.SQLRestriction;

import com.eqms.common.RegulatedEntity;
import com.eqms.signatures.SignatureService;
import com.eqms.workflows.WorkflowAware;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import lombok.Getter;
import lombok.Setter;

/**
 * A controlled document (SOP, work instruction, etc.). Regulated record: optimistic locking,
 * soft delete, audit columns (from {@link RegulatedEntity}). Implements {@link WorkflowAware} so its
 * status is driven through the shared WorkflowService — the module never mutates status directly.
 *
 * <p>The status is stored in a field named {@code documentStatus} (typed accessors generated by
 * Lombok) while the {@link WorkflowAware} contract is satisfied by the String-based
 * {@link #getStatus()}/{@link #setStatus(String)} below.</p>
 */
@Entity
@Table(name = "documents")
@Getter
@Setter
@SQLDelete(sql = "UPDATE documents SET deleted_at = now(), version = version + 1 WHERE id = ? AND version = ?")
@SQLRestriction("deleted_at IS NULL")
public class Document extends RegulatedEntity implements WorkflowAware {

    @Column(name = "document_number", nullable = false, length = 40, unique = true)
    private String documentNumber;

    @Column(name = "title", nullable = false, length = 400)
    private String title;

    @Enumerated(EnumType.STRING)
    @Column(name = "document_type", nullable = false, length = 40)
    private DocumentType documentType;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 40)
    private DocumentStatus documentStatus = DocumentStatus.DRAFT;

    @Column(name = "content", columnDefinition = "text")
    private String content;

    @Column(name = "major_version", nullable = false)
    private int majorVersion = 1;

    @Column(name = "effective_date")
    private Instant effectiveDate;

    @Column(name = "next_review_date")
    private Instant nextReviewDate;

    @Column(name = "review_period_months")
    private Integer reviewPeriodMonths;

    @Column(name = "superseded_by_id")
    private Long supersededById;

    @Column(name = "submitted_by")
    private Long submittedBy;

    @Column(name = "folder_id")
    private Long folderId;

    @Column(name = "checked_out_by")
    private Long checkedOutBy;

    @Column(name = "checked_out_at")
    private Instant checkedOutAt;

    // --- WorkflowAware ---------------------------------------------------------------------

    @Override
    @Transient
    public String getRecordType() {
        return "Document";
    }

    @Override
    @Transient
    public String getStatus() {
        return documentStatus.name();
    }

    @Override
    public void setStatus(String status) {
        this.documentStatus = DocumentStatus.valueOf(status);
    }

    /** Binds an electronic signature to the document's current title/content/version (rule 4). */
    @Override
    @Transient
    public String workflowContentHash() {
        return SignatureService.sha256Hex(
                (title == null ? "" : title) + "|"
                        + (content == null ? "" : content) + "|"
                        + majorVersion);
    }
}
