package com.eqms.oosmanagement;

public enum OosStatus {
    DRAFT,
    REPORTED,
    INITIAL_ASSESSMENT,
    AWAITING_REPEAT,
    INVESTIGATING,
    DISPOSITION_DETERMINED,
    CLOSED,
    LAB_INVESTIGATION,
    QA_REVIEW,
    RETEST_PENDING,
    RESAMPLE_PENDING,
    CAPA_REQUIRED,
    DISPOSITION_PENDING,
    REOPENED,
    CANCELLED
}
