package com.eqms.deviations;

/** Categorisation of the deviation by process/area type. */
public enum DeviationCategory {
    PROCESS_DEVIATION,
    PROCEDURE_DEVIATION,
    PRODUCT_DEVIATION,
    MATERIAL_DEVIATION,
    EQUIPMENT_DEVIATION,
    LABORATORY_DEVIATION,
    CLEANING_DEVIATION,
    ENVIRONMENTAL_DEVIATION,
    DOCUMENTATION_DEVIATION,
    TRAINING_DEVIATION,
    SUPPLIER_DEVIATION,
    PACKAGING_DEVIATION,
    STORAGE_WAREHOUSE_DEVIATION,
    DATA_INTEGRITY_DEVIATION,
    SAFETY_DEVIATION,
    OTHER
}
